version: '3'
services:
  tp2back:
    image: 214399b636ce
    ports:
      - "8080:8080"
    environment:
      - ENVIRONMENT=dev
  tp2front:
    image: 85966fbbd578
    ports:
      - "8081:8081"
    environment:
      - APP_PORT=8081
      - WS_BACK_URL=172.17.0.1
